### ISSUE TITLE
Environment Setup

### ISSUE THREAD

**Issue by nik1sto** [trasse/OpSeF-IV#2]
Dear Mr Rasse,

when trying to set up the environment with conda via the yaml file, I get a long list of ResolvePackageNotFound. Therefore, I wondered, if you have also an requirements file I could use to set up the environment. Thank you in advance!

**Comment by trasse** [comment]
Dear nik1sto,

I just pushed the requirements.
Could you please confirm that it worked & name the system you use.
Do you use Windows?

I tried everything only on Ubuntu.

Kind regards
Tobias

**Comment by nik1sto** [comment]
Thank you for the quick response!

Yes, I am using Windows and unfortunately, it still doesn't work. So I should switch to my Linux to be able to use the exact same builds.

**Comment by trasse** [comment]
Yes, this is one option.

Or if you prefer Windows you can do the following:

1) Create an environment for python 3.6.
2) Get Tensorflow to work in it (on the GPU!!)
3) Make a copy (to be save)
4) In the copy: Install StarDist, Install Cellpose (verify that it works), Install CSBDeep.
(if you have trouble look in the respective FAQ for advise)

5) (Make again a copy)
5) Compare what you already have with the requirements file (should be > 80%)
6) Install all missing libraries manually.
    Some will work with conda, for others you need to use pip.

Then (most important):
( => please make a yaml file and share it! (all Windows users will appreciate this a lot!)

**Comment by nik1sto** [comment]
Thank you for the detailed steps!
I have finally gained access a cluster now though, which is Linux based.

**Comment by saskra** [comment]
I did not get a consistent environment on Ubuntu with the given files, so I made my own ones. This one for conda:
```
numpy
tifffile
matplotlib
opencv
pandas
networkx
scipy
scikit-image
scikit-learn
tensorflow-gpu<=1.15.0
keras-gpu
mxnet
```

Additionally this one for pip:
```
csbdeep
cellpose
n2v
readlif
stardist
```

**Comment by trasse** [comment]
Dear Saskra,

Thanks a lot for sharing the solution that worked for you!
I had bad experiences with letting conda choose the version of tensorflow to use.
But this might depend on the exact setup.

Kind regards

Tobias

**Comment by saskra** [comment]
Yes, Tensorflow and CUDA tend to make problems. In this case I think your versions were not working with my graphics card driver. The only restriction I made was not to use Tensorflow 2.
